#!/bin/bash
# Gitee 部署配置脚本

echo "🚀 配置 Gitee 部署"
echo "=================="
echo ""
echo "请按以下步骤操作："
echo ""
echo "1️⃣ 访问 https://gitee.com 登录/注册"
echo ""
echo "2️⃣ 创建新仓库："
echo "   - 仓库名称: daily-brief"
echo "   - 是否开源: 公开"
echo "   - 初始化: 不要勾选（因为已有代码）"
echo ""
echo "3️⃣ 创建完成后，获取仓库地址："
echo "   类似: https://gitee.com/你的用户名/daily-brief.git"
echo ""
echo "4️⃣ 把下面的命令复制到本地执行："
echo ""
echo "   cd /root/.openclaw/workspace/daily-brief"
echo "   git remote add gitee https://gitee.com/你的用户名/daily-brief.git"
echo "   git push gitee main"
echo ""
echo "5️⃣ 开启 Gitee Pages："
echo "   - 进入仓库 → 服务 → Gitee Pages"
echo "   - 选择 main 分支，/ (root) 目录"
echo "   - 点击 开启"
echo ""
echo "✅ 完成后，访问地址："
echo "   https://你的用户名.gitee.io/daily-brief/"
echo ""
echo "💡 建议：配置 GitHub Actions 自动同步到 Gitee"
